import * as maplibregl from 'https://unpkg.com/maplibre-gl@^6.11.2/dist/maplibre-gl.mjs';

const JOZI = {center:[28.0473,-26.2041], zoom:11.3};
const places = [
 {name:'Bree Street Taxi Rank',cat:'taxi',lat:-26.20081,lng:28.03653,area:'CBD / Newtown edge',clue:'A major inner-city taxi node just east of Newtown, close to the Queen Elizabeth Bridge and Metro Mall.',fact:'Bree Street and Metro Mall form one of the CBD’s most important minibus-taxi interchange areas.',modes:['taxi','walk','drive']},
 {name:'Noord / Park Central Taxi Rank',cat:'taxi',lat:-26.1974,lng:28.0485,area:'Joubert Park / CBD',clue:'Find the busy rank on the northern side of the CBD, close to Joubert Park and the Johannesburg Art Gallery.',fact:'This rank is often referred to as Noord or MTN Noord and sits within easy reach of Park Station.',modes:['taxi','walk']},
 {name:'Randburg Taxi Rank',cat:'taxi',lat:-26.09545,lng:28.00694,area:'Randburg CBD',clue:'This taxi rank sits near the Randburg Civic Centre and licensing department, north-west of the inner city.',fact:'Randburg’s rank is a useful orientation point for movement between the northern suburbs and other Johannesburg nodes.',modes:['taxi','drive']},
 {name:'Park Station',cat:'landmark',lat:-26.19767,lng:28.04231,area:'Braamfontein / CBD edge',clue:'Johannesburg’s central rail hub: Gautrain, commuter rail and long-distance travel converge here.',fact:'Park Station is one of Johannesburg’s biggest transport anchors and sits at the northern edge of the CBD.',modes:['taxi','walk','drive','cycle']},
 {name:'Constitution Hill',cat:'landmark',lat:-26.190217,lng:28.041916,area:'Braamfontein',clue:'Home of the Constitutional Court, on the ridge between Braamfontein and Hillbrow.',fact:'Constitution Hill is both a historic prison precinct and the home of South Africa’s Constitutional Court.',modes:['walk','cycle','drive']},
 {name:'Maboneng Precinct',cat:'landmark',lat:-26.20383,lng:28.05951,area:'Jeppestown / eastern CBD',clue:'The arts-and-lifestyle precinct east of the CBD, around Fox Street and Main Street Life.',fact:'Maboneng is a useful mental marker for the eastern side of the inner city.',modes:['walk','cycle','drive','taxi']},
 {name:'FNB Stadium',cat:'landmark',lat:-26.23473,lng:27.98264,area:'Nasrec',clue:'The huge calabash-shaped football stadium south-west of the CBD, near Nasrec.',fact:'FNB Stadium is a strong landmark for orienting yourself between the CBD and Soweto.',modes:['drive','taxi','cycle']},
 {name:'Orlando Stadium',cat:'landmark',lat:-26.23189,lng:27.92289,area:'Orlando East, Soweto',clue:'A historic football ground in Orlando East, west of FNB Stadium.',fact:'Orlando Stadium is one of Soweto’s best-known sporting landmarks.',modes:['taxi','drive','cycle']},
 {name:'Maponya Mall',cat:'landmark',lat:-26.25828,lng:27.90142,area:'Pimville, Soweto',clue:'A major shopping centre on Chris Hani Road, farther west in Soweto.',fact:'Maponya Mall is a practical anchor for the south-western part of the city.',modes:['taxi','drive']},
 {name:'Sandton Gautrain Station',cat:'landmark',lat:-26.1078,lng:28.0582,area:'Sandton CBD',clue:'The underground Gautrain station by Rivonia Road, near Sandton City and Nelson Mandela Square.',fact:'Sandton Station is the key Gautrain interchange for the northern Johannesburg business district.',modes:['drive','taxi','walk','cycle']},
 {name:'Rosebank Gautrain Station',cat:'landmark',lat:-26.14664,lng:28.04469,area:'Rosebank',clue:'The underground station beneath Oxford Road, opposite The Zone.',fact:'Rosebank sits on the north-south Gautrain corridor between Park Station and Sandton.',modes:['walk','drive','cycle','taxi']},
 {name:'M1 / Empire Road',cat:'road',lat:-26.1852,lng:28.0177,area:'Braamfontein / Parktown',clue:'Find the major M1 interchange used to reach Braamfontein, Wits and Parktown from the motorway.',fact:'Empire Road is one of the most useful east–west approaches to Braamfontein and Wits.',modes:['drive','taxi']},
 {name:'Oxford Road / Bolton Road',cat:'road',lat:-26.1552,lng:28.0434,area:'Rosebank',clue:'A major north–south arterial through Rosebank. Guess near its junction with Bolton Road.',fact:'Oxford Road is a key surface-road spine linking Rosebank toward Illovo and the inner city.',modes:['drive','cycle','taxi']},
 {name:'Jan Smuts Avenue / Empire Road',cat:'road',lat:-26.1831,lng:28.0150,area:'Braamfontein / Parktown',clue:'Guess the junction where Jan Smuts meets Empire Road, close to Wits and the M1 approaches.',fact:'Jan Smuts is one of the city’s most useful north–south orientation roads.',modes:['drive','cycle','taxi']},
 {name:'Rivonia Road / West Street',cat:'road',lat:-26.1080,lng:28.0580,area:'Sandton CBD',clue:'The Sandton intersection beside the Gautrain station and only a short walk from Nelson Mandela Square.',fact:'Rivonia Road is one of Sandton’s main north–south roads.',modes:['drive','walk','cycle']},
 {name:'Chris Hani Road / Maponya Mall',cat:'road',lat:-26.2580,lng:27.9018,area:'Pimville, Soweto',clue:'Place your pin on the major Soweto arterial running past Maponya Mall.',fact:'Chris Hani Road is a major east–west movement corridor through Soweto.',modes:['drive','taxi','cycle']},
 {name:'BP near Sandton City',cat:'garage',lat:-26.11004,lng:28.05526,area:'Sandton CBD',clue:'Find the BP fuel stop just south-west of the Gautrain station and Sandton City.',fact:'Fuel stops near major nodes are useful “micro-landmarks” when you drive regularly in a new city.',modes:['drive','cycle']},
 {name:'BP Grayston Drive',cat:'garage',lat:-26.09786,lng:28.05976,area:'Sandown',clue:'A BP on the Grayston corridor, north of central Sandton and near Sandown.',fact:'Grayston Drive is a common motorway-to-Sandton approach; service stations along it make useful navigation anchors.',modes:['drive']},
 {name:'Engen Alexandra / Lenin Drive',cat:'garage',lat:-26.10469,lng:28.11738,area:'Alexandra',clue:'An Engen on Lenin Drive near Alex Mall, east of Sandton.',fact:'This location helps build a sense of how Alexandra sits east of the Sandton business district.',modes:['drive','taxi']},
 {name:'BP Bara',cat:'garage',lat:-26.26051,lng:27.94696,area:'Diepkloof / Bara',clue:'Find the fuel stop near the Bara taxi-rank area, west of the N1 and south-west of the CBD.',fact:'The Bara/Diepkloof area is a major movement node between Soweto and central Johannesburg.',modes:['drive','taxi']}
];

const $=s=>document.querySelector(s);
const state={mode:'walk',category:'mixed',rounds:[],i:0,score:0,guess:null,guessMarker:null,targetMarker:null,hint:false,distances:[]};
const highScore=()=>Number(localStorage.getItem('joziQuestHigh')||0);
const paintHighScore=()=>{$('#homeHighScore').textContent=highScore()?highScore().toLocaleString():'—'};
let map;

function setupChips(group,key){document.querySelectorAll(group+' .choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll(group+' .choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');state[key]=b.dataset[key];}));}
setupChips('#transportChips','mode');setupChips('#categoryChips','category');paintHighScore();

$('#startBtn').addEventListener('click',startGame);$('#homeBtn').addEventListener('click',showWelcome);$('#againBtn').addEventListener('click',startGame);$('#changeBtn').addEventListener('click',showWelcome);$('#submitBtn').addEventListener('click',submitGuess);$('#nextBtn').addEventListener('click',nextRound);$('#hintBtn').addEventListener('click',useHint);$('#resetViewBtn').addEventListener('click',()=>map.flyTo({...JOZI,pitch:45,bearing:-12}));$('#tiltBtn').addEventListener('click',()=>map.easeTo({pitch:map.getPitch()>20?0:58,duration:650}));

function filteredPlaces(){let pool=places.filter(p=>state.category==='mixed'||p.cat===state.category);let modePool=pool.filter(p=>p.modes.includes(state.mode));if(modePool.length>=5)pool=modePool;return pool;}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function startGame(){state.rounds=shuffle(filteredPlaces()).slice(0,5);if(state.rounds.length<5)state.rounds=shuffle(places.filter(p=>state.category==='mixed'||p.cat===state.category)).slice(0,5);state.i=0;state.score=0;state.distances=[];$('#scoreValue').textContent='0';$('#welcomePanel').classList.add('hidden');$('#finishPanel').classList.add('hidden');$('#gamePanel').classList.remove('hidden');if(!map)initMap();else map.resize();setTimeout(loadRound,180)}
function showWelcome(){if(map){clearMarkers();clearLine();}$('#gamePanel').classList.add('hidden');$('#finishPanel').classList.add('hidden');$('#welcomePanel').classList.remove('hidden')}
function initMap(){map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:JOZI.center,zoom:JOZI.zoom,pitch:45,bearing:-12,attributionControl:true});map.addControl(new maplibregl.NavigationControl({showCompass:true}),'top-right');map.on('load',()=>{tryAdd3D()});map.on('click',e=>{if($('#resultBox').classList.contains('hidden'))placeGuess(e.lngLat)});map.on('error',()=>{$('#instruction').textContent='Map connection problem. Check your internet connection and reload.'})}
function tryAdd3D(){const source=map.getSource('openmaptiles')?'openmaptiles':null;if(!source||map.getLayer('jozi-3d'))return;const firstSymbol=(map.getStyle().layers||[]).find(l=>l.type==='symbol')?.id;try{map.addLayer({id:'jozi-3d',source,'source-layer':'building',minzoom:14,type:'fill-extrusion',filter:['==',['get','hide_3d'],false],paint:{'fill-extrusion-color':'#3b413f','fill-extrusion-height':['coalesce',['get','render_height'],['get','height'],8],'fill-extrusion-base':['coalesce',['get','render_min_height'],0],'fill-extrusion-opacity':.78}},firstSymbol)}catch(e){console.debug('3D layer unavailable',e)}}
function loadRound(){clearMarkers();clearLine();state.guess=null;state.hint=false;$('#resultBox').classList.add('hidden');$('#submitBtn').disabled=true;$('#hintBtn').disabled=false;const p=state.rounds[state.i];$('#roundLabel').textContent=`ROUND ${state.i+1} / 5`;$('#roundLabelTop').textContent=`Round ${state.i+1}`;$('#progressBar').style.width=`${(state.i+1)*20}%`;$('#modeBadge').textContent=state.mode.toUpperCase();$('#categoryLabel').textContent=({taxi:'TAXI RANK',road:'ROAD',landmark:'LANDMARK',garage:'GARAGE / FUEL'})[p.cat];$('#categoryIcon').textContent=({taxi:'↔',road:'╱',landmark:'◎',garage:'⛽'})[p.cat];$('#questionTitle').textContent=p.name;$('#questionClue').textContent=p.clue;$('#transportTip').textContent=transportTip(p);$('#instruction').textContent='Click anywhere on the map to place your guess.';map.flyTo({...JOZI,pitch:45,bearing:-12,duration:700})}
function transportTip(p){const tips={walk:`Walking lens: learn nearby anchors and how ${p.area} connects on foot.`,drive:'Driving lens: think in arterials, motorway approaches and large visual anchors.',taxi:'Taxi lens: think in ranks, interchanges and the corridor this place belongs to.',cycle:'Cycling lens: use main roads and landmarks, but keep an eye on distance and topography.'};return tips[state.mode]}
function placeGuess(ll){state.guess=[ll.lng,ll.lat];if(state.guessMarker)state.guessMarker.remove();const el=document.createElement('div');el.className='guess-marker';state.guessMarker=new maplibregl.Marker({element:el}).setLngLat(state.guess).addTo(map);$('#submitBtn').disabled=false;$('#instruction').textContent='Pin placed. Move it by clicking somewhere else, or lock your guess.'}
function km(a,b){const R=6371,dLat=(b[1]-a[1])*Math.PI/180,dLon=(b[0]-a[0])*Math.PI/180,la1=a[1]*Math.PI/180,la2=b[1]*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function submitGuess(){if(!state.guess)return;const p=state.rounds[state.i],target=[p.lng,p.lat],d=km(state.guess,target);state.distances.push(d);const scale={walk:2.2,cycle:4,drive:7,taxi:6}[state.mode];let pts=Math.round(1000*Math.exp(-d/scale));if(d<.15)pts=1000;if(state.hint)pts=Math.max(0,pts-150);state.score+=pts;$('#scoreValue').textContent=state.score;$('#roundPoints').textContent=`+${pts}`;$('#distanceText').textContent=d<1?`${Math.round(d*1000)} m away`:`${d.toFixed(1)} km away`;$('#learningText').textContent=p.fact;$('#resultBox').classList.remove('hidden');$('#submitBtn').disabled=true;$('#hintBtn').disabled=true;const el=document.createElement('div');el.className='target-marker';state.targetMarker=new maplibregl.Marker({element:el,anchor:'bottom'}).setLngLat(target).addTo(map);drawLine(state.guess,target);const bounds=new maplibregl.LngLatBounds();bounds.extend(state.guess);bounds.extend(target);map.fitBounds(bounds,{padding:{top:100,bottom:260,left:80,right:80},maxZoom:14,duration:900})}
function drawLine(a,b){clearLine();map.addSource('guess-line',{type:'geojson',data:{type:'Feature',geometry:{type:'LineString',coordinates:[a,b]}}});map.addLayer({id:'guess-line',type:'line',source:'guess-line',paint:{'line-color':'#ff6b35','line-width':3,'line-dasharray':[2,2]}})}
function clearLine(){if(!map)return;if(map.getLayer('guess-line'))map.removeLayer('guess-line');if(map.getSource('guess-line'))map.removeSource('guess-line')}
function clearMarkers(){state.guessMarker?.remove();state.targetMarker?.remove();state.guessMarker=null;state.targetMarker=null}
function useHint(){if(state.hint)return;state.hint=true;const p=state.rounds[state.i];$('#questionClue').textContent+=` Hint: focus on ${p.area}.`;$('#hintBtn').disabled=true}
function nextRound(){if(state.i<4){state.i++;loadRound()}else finishGame()}
function finishGame(){clearMarkers();clearLine();$('#gamePanel').classList.add('hidden');$('#finishPanel').classList.remove('hidden');$('#finalScore').textContent=state.score;const avg=state.distances.reduce((a,b)=>a+b,0)/state.distances.length;const grade=state.score>=4200?'Strong city sense':state.score>=3000?'Good bearings':state.score>=1800?'Getting oriented':'Fresh arrival';$('#finishHeading').textContent=grade;$('#finishCopy').textContent=state.score>=3000?'You are building a useful mental map of Johannesburg. Repeat with a different transport mode to learn the city from another perspective.':'The fastest improvement comes from replaying the same category: your second run will feel much easier.';const best=Math.min(...state.distances);$('#finishStats').innerHTML=`<div class="stat"><strong>${avg.toFixed(1)} km</strong><span>AVG ERROR</span></div><div class="stat"><strong>${best<1?Math.round(best*1000)+' m':best.toFixed(1)+' km'}</strong><span>BEST GUESS</span></div><div class="stat"><strong>${state.mode}</strong><span>TRAVEL LENS</span></div>`;const high=Math.max(Number(localStorage.getItem('joziQuestHigh')||0),state.score);localStorage.setItem('joziQuestHigh',high);paintHighScore()}